version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: mongo1
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db/mongo1

  mysql:
    image: mysql
    container_name: mysql1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - "3307:3306"

volumes:
  mongodb_data: